## Jump to P+K if (Xj) in range

In IEEE floating-point, a calue is *in range* if it is neither an infinity nor a **NaN**.
An infinity can be generated by
1. An arithmetic computation that overflows the largest representable number (e.g., adding two very large positive numbers);
2. An arithmetic computation that underflows the smallest representable number (e.g., adding two very large absolute value negative numbers);
3. Dividing a positive number by 0 (e.g., $`1.0/0 = +\infty`$);
